import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Akshay Shinde',
  description: 'Generated by Akshay as his portfolio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <nav style={{position: 'absolute', zIndex: 9999}}> Akshay Shinde | Next Dev</nav> */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
